### ISSUE TITLE
Exception thrown when selecting Main Menu > New Game

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/MonoGameJam#524]
#### Steps
Following the characters deaths, from the Main Menu I selected New Game, and immediately received an exception `Collection was modified; enumeration operation may not execute.`

#### State
In `NeedlesslyComplexMainGame.Update`:
![image.png](https://zube.io/files/enigmadragons/fc8b1497ac8e68e5bff5ad4f3169f706-image.png)

![image.png](https://zube.io/files/enigmadragons/a7602b35f5534a5e24d573411c4556d8-image.png)

#### Stack Trace
```
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at MonoDragons.Core.Scenes.SceneContainer.Update(TimeSpan delta) in C:\\source\\MonoGameJam\\src\\MonoDragons.Core\\Scenes\\SceneContainer.cs:line 44
at MonoDragons.Core.Scenes.CurrentScene.Update(TimeSpan delta) in C:\\source\\MonoGameJam\\src\\MonoDragons.Core\\Scenes\\CurrentScene.cs:line 21
at MonoDragons.Core.Render.HideViewportExternals.Update(TimeSpan delta) in C:\\source\\MonoGameJam\\src\\MonoDragons.Core\\Render\\HideViewportExternals.cs:line 29
at MonoDragons.Core.Engine.NeedlesslyComplexMainGame.Update(GameTime gameTime) in C:\\source\\MonoGameJam\\src\\MonoDragons.Core\\Engine\\NeedlesslyComplexMainGame.cs:line 133
```

#### Output Window
```
(~3200 lines of otherwise mundane game play)
ZeroFootPrintSociety.AI.AIActionQueued
ZeroFootPrintSociety.CoreGame.StateEvents.ActionConfirmed
ZeroFootPrintSociety.CoreGame.StateEvents.ActionResolved
ZeroFootPrintSociety.CoreGame.StateEvents.TurnEnded
ZeroFootPrintSociety.CoreGame.StateEvents.TurnBegun
ZeroFootPrintSociety.CoreGame.StateEvents.MovementOptionsAvailable
The thread 0x52fc has exited with code 0 (0x0).
The thread 0x312c has exited with code 0 (0x0).
The thread 0x5264 has exited with code 0 (0x0).
The thread 0x3300 has exited with code 0 (0x0).
The thread 0x4d9c has exited with code 0 (0x0).
The thread 0x4164 has exited with code 0 (0x0).
The thread 0xa34 has exited with code 0 (0x0).
The thread 0x31e0 has exited with code 0 (0x0).
The thread 0x4eb8 has exited with code 0 (0x0).
The thread 0x39d4 has exited with code 0 (0x0).
The thread 0x2310 has exited with code 0 (0x0).
The thread 0x57b0 has exited with code 0 (0x0).
The thread 0x52bc has exited with code 0 (0x0).
The thread 0x4184 has exited with code 0 (0x0).
The thread 0x27e8 has exited with code 0 (0x0).
ZeroFootPrintSociety.CoreGame.StateEvents.MovementConfirmed
ZeroFootPrintSociety.CoreGame.StateEvents.Moved
ZeroFootPrintSociety.CoreGame.StateEvents.MoveResolved
ZeroFootPrintSociety.CoreGame.StateEvents.TilesPercieved
ZeroFootPrintSociety.CoreGame.StateEvents.MovementFinished
ZeroFootPrintSociety.CoreGame.RangedTargetsAvailable
ZeroFootPrintSociety.CoreGame.ActionOptionsAvailable
ZeroFootPrintSociety.CoreGame.StateEvents.TilesSeen
ZeroFootPrintSociety.CoreGame.StateEvents.ActionSelected
ZeroFootPrintSociety.CoreGame.Mechanics.Events.ShootSelected
ZeroFootPrintSociety.CoreGame.StateEvents.RangedTargetInspected
ZeroFootPrintSociety.CoreGame.StateEvents.ActionReadied
ZeroFootPrintSociety.CoreGame.ShotProposed
ZeroFootPrintSociety.CoreGame.StateEvents.ActionConfirmed
ZeroFootPrintSociety.CoreGame.ShotConfirmed
ZeroFootPrintSociety.CoreGame.ActionEvents.ShotFired
ZeroFootPrintSociety.CoreGame.ActionEvents.ShotHit
ZeroFootPrintSociety.GUI.ShotAnimationsFinished
ZeroFootPrintSociety.CoreGame.ActionEvents.ShotFired
ZeroFootPrintSociety.CoreGame.ActionEvents.ShotHit
ZeroFootPrintSociety.GUI.ShotAnimationsFinished
ZeroFootPrintSociety.CoreGame.StateEvents.CharacterDeceased
ZeroFootPrintSociety.CoreGame.StateEvents.ActionResolved
ZeroFootPrintSociety.CoreGame.StateEvents.GameOver
ZeroFootPrintSociety.CoreGame.StateEvents.TurnEnded
The thread 0x4498 has exited with code 0 (0x0).
The thread 0x2228 has exited with code 0 (0x0).
The thread 0x4bc4 has exited with code 0 (0x0).
The thread 0x1ba4 has exited with code 0 (0x0).
The thread 0x5c44 has exited with code 0 (0x0).
The thread 0x587c has exited with code 0 (0x0).
The thread 0x559c has exited with code 0 (0x0).
The thread 0x5504 has exited with code 0 (0x0).
The thread 0x2f4c has exited with code 0 (0x0).
The thread 0x26d0 has exited with code 0 (0x0).
The thread 0x31ec has exited with code 0 (0x0).
The thread 0x33a0 has exited with code 0 (0x0).
The thread 0x1b08 has exited with code 0 (0x0).
The thread 0x4be8 has exited with code 0 (0x0).
The thread 0x6a4 has exited with code 0 (0x0).
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
```

**Comment by SilasReinagel** [comment]
Isn't this a duplicate of EnigmaDragons/MonoGameJam#522 ?
